services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      default:
        aliases:
          - zookeeper
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    user: "1000:1000"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.17.0.1:9092,PLAINTEXT_HOST://172.17.0.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      default:
        aliases:
          - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kafka-connector: 
    build:
      context: ./kafka-connector
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 9099:9099
    links:
      - kafka
    networks:
      default:
        aliases:
          - kafka-connector

  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db
    links:
      - db
      - kafka:kafka-connector
    networks:
      default:
        aliases:
          - fhir

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cbc-processor:
    build: 
        context: ./analisehemograma
        dockerfile: Dockerfile
    container_name: cbc-processor
    ports:
        - "8081:8080"
        - "5005:5005" # Expose the debug port
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/processor
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

configs:
  hapi:
    file: ./hapi/hapi.application.yaml