services:
    app:
        build: .
        ports:
            - "8080:8080"
            - "5005:5005" # Expose the debug port
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=batata
            - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
        depends_on:
            db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 512M

    db:
        image: postgres:18
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_PASSWORD=batata
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
